name: swim-adsb
dependencies:
  - _libgcc_mutex=0.1=main
  - atomicwrites=1.3.0=py37_1
  - attrs=19.3.0=py_0
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - coverage=5.0=py37h7b6447c_0
  - importlib_metadata=1.4.0=py37_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - more-itertools=8.0.2=py_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1d=h7b6447c_3
  - packaging=20.1=py_0
  - pip=20.0.2=py37_0
  - pluggy=0.13.1=py37_0
  - py=1.8.1=py_0
  - pyparsing=2.4.6=py_0
  - pytest=5.0.1=py37_0
  - pytest-cov=2.8.1=py_0
  - python=3.7.6=h0371630_2
  - pyyaml=5.2=py37h7b6447c_0
  - readline=7.0=h7b6447c_5
  - setuptools=45.1.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - cachetools==4.0.0
    - chardet==3.0.4
    - idna==2.8
    - opensky-network-client==0.0.6
    - pubsub-facades==0.0.2
    - python-qpid-proton==0.30.0
    - requests==2.22.0
    - rest-client==0.1.1
    - subscription-manager-client==0.0.9
    - swim-backend==0.0.6
    - swim-qpid-proton==0.0.2
    - urllib3==1.25.8
