name: swim-adsb
dependencies:
  - atomicwrites=1.3.0=py37_1
  - attrs=19.1.0=py37_1
  - ca-certificates=2019.5.15=0
  - certifi=2019.3.9=py37_0
  - coverage=4.5.3=py37h7b6447c_0
  - importlib_metadata=0.17=py37_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - more-itertools=7.0.0=py37_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1c=h7b6447c_1
  - packaging=19.0=py37_0
  - pip=19.1.1=py37_0
  - pluggy=0.12.0=py_0
  - py=1.8.0=py37_0
  - pyparsing=2.4.0=py_0
  - pytest=4.6.2=py37_0
  - pytest-cov=2.7.1=py_0
  - python=3.7.3=h0371630_0
  - pyyaml=5.1=py37h7b6447c_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zipp=0.5.1=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - cachetools==3.1.1
    - chardet==3.0.4
    - idna==2.8
    - opensky-network-client==0.0.5
    - python-qpid-proton==0.28.0
    - requests==2.22.0
    - rest-client==0.0.5
    - subscription-manager-client==0.0.8
    - swim-pubsub==1.3.2
    - urllib3==1.25.3
