name: swim-adsb
dependencies:
  - atomicwrites=1.3.0=py37_1
  - attrs=19.1.0=py37_1
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - coverage=4.5.3=py37h7b6447c_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - more-itertools=7.0.0=py37_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1b=h7b6447c_1
  - pip=19.1.1=py37_0
  - pluggy=0.11.0=py_0
  - py=1.8.0=py37_0
  - pytest=4.5.0=py37_0
  - pytest-cov=2.6.1=py37_0
  - python=3.7.3=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - chardet==3.0.4
    - idna==2.8
    - opensky-network-client==0.0.2
    - requests==2.22.0
    - rest-client==0.0.5
    - swim-pubsub==0.0.1
    - urllib3==1.25.2
